[profile.default]
src = 'contracts'
out = 'out'
cache_path = 'cache_forge'
libs = ['node_modules', 'lib']
test = 'test/foundry'

[profile.endpoints]
goerli = "${GOERLI_RPC_URL}"
local = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"

[profile.compilers]
solc = "0.8.20"

[etherscan]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
